[package]
name = "gitql-engine"
authors = ["AmrDeveloper"]
version = "0.19.0"
edition = "2021"
description = "GitQL Engine"
repository = "https://github.com/amrdeveloper/gql/tree/main/crates/gitql-engine"
license = "MIT"

[dependencies]
gitql-ast = { path = "../gitql-ast", version = "0.17.0" }
regex = "1.10.4"
gix = { workspace = true, features = ["blob-diff"] }
